# -*- coding: utf-8 -*-
"""
TYP Generator for Garmin Export Plugin
Генератор TYP-файлов (typ.txt) из символики слоёв QGIS

TYP-файл определяет внешний вид объектов на устройстве Garmin (цвета
полигонов, толщину и цвет линий, иконки POI). Текстовый typ.txt
компилируется самим mkgmap: достаточно передать его дополнительным
входным файлом. Формат описан в "TYP Compiler Manual" mkgmap.

Модуль разделён на две части:
  - TypFileBuilder: чистый построитель текста typ.txt (без QGIS),
    полностью тестируемый;
  - extract_layer_style / build_typ_from_layers: чтение символики QGIS.

Author: Кобяков Александр Викторович (Alex Kobyakov)
Email: kobyakov@lesburo.ru
Year: 2025-2026
"""


# Символы для палитры XPM (без кавычек и обратного слэша)
_XPM_CHARS = (
    'abcdefghijklmnopqrstuvwxyz'
    'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    '0123456789'
    '.,:;!?#$%&*+-/<=>@[]^_`{|}~ '
)

MAX_DRAW_ORDER = 8


def _normalize_hex_color(color, default='#808080'):
    """Приведение цвета к виду #rrggbb"""
    if not color:
        return default
    text = str(color).strip()
    if not text.startswith('#'):
        text = '#' + text
    if len(text) == 4:  # #rgb -> #rrggbb
        text = '#' + ''.join(ch * 2 for ch in text[1:])
    if len(text) >= 7:
        return text[:7].lower()
    return default


class TypFileBuilder:
    """Построитель текстового TYP-файла (typ.txt) для компиляции mkgmap"""

    def __init__(self, family_id, product_id=1, code_page='1252'):
        self.family_id = int(family_id)
        self.product_id = int(product_id)
        self.code_page = str(code_page)
        self.polygons = []   # (type_code, color, draw_order, label)
        self.lines = []      # (type_code, color, width, border_color, border_width, label)
        self.points = []     # (type_code, pixels, label)

    # ------------------------------------------------------------------
    # Добавление элементов
    # ------------------------------------------------------------------

    def add_polygon(self, type_code, color, draw_order=3, label=None):
        """Полигон со сплошной заливкой.

        Args:
            type_code: числовой тип Garmin (например 0x16)
            color: '#rrggbb'
            draw_order: порядок отрисовки 1..8 (выше = поверх)
            label: подпись типа (необязательно)
        """
        order = max(1, min(MAX_DRAW_ORDER, int(draw_order)))
        self.polygons.append(
            (int(type_code), _normalize_hex_color(color), order, label))

    def add_line(self, type_code, color, width=2, border_color=None,
                 border_width=0, label=None):
        """Линия заданной толщины (в пикселях устройства).

        Args:
            type_code: числовой тип Garmin (например 0x06)
            color: '#rrggbb' основной цвет
            width: толщина линии в пикселях (1..15)
            border_color: цвет каймы или None
            border_width: толщина каймы в пикселях
        """
        width = max(1, min(15, int(round(width))))
        border_width = max(0, min(10, int(round(border_width))))
        self.lines.append((
            int(type_code), _normalize_hex_color(color), width,
            _normalize_hex_color(border_color) if border_color else None,
            border_width, label))

    def add_point(self, type_code, pixels, label=None):
        """POI с иконкой.

        Args:
            type_code: числовой тип Garmin (например 0x2f00)
            pixels: матрица (список строк) значений '#rrggbb', '#rrggbbaa'
                или None (прозрачный пиксель); все строки одной длины
            label: подпись типа (необязательно)
        """
        if not pixels or not pixels[0]:
            return
        self.points.append((int(type_code), pixels, label))

    # ------------------------------------------------------------------
    # Генерация текста
    # ------------------------------------------------------------------

    def build(self):
        """Возвращает содержимое typ.txt"""
        blocks = [
            '; Generated by Garmin Export Plugin for QGIS',
            '; TYP source file for mkgmap TYP compiler',
            '',
            '[_id]',
            'FID={0}'.format(self.family_id),
            'ProductCode={0}'.format(self.product_id),
            'CodePage={0}'.format(self.code_page),
            '[end]',
            '',
        ]

        # [_drawOrder]: полигон не из списка не отображается вовсе,
        # поэтому секция обязательна при наличии полигонов
        if self.polygons:
            blocks.append('[_drawOrder]')
            for type_code, _color, order, _label in self.polygons:
                blocks.append('Type={0},{1}'.format(
                    self._format_type(type_code), order))
            blocks.append('[end]')
            blocks.append('')

        for type_code, color, _order, label in self.polygons:
            blocks.extend(self._polygon_block(type_code, color, label))
            blocks.append('')

        for entry in self.lines:
            blocks.extend(self._line_block(*entry))
            blocks.append('')

        for type_code, pixels, label in self.points:
            blocks.extend(self._point_block(type_code, pixels, label))
            blocks.append('')

        return '\n'.join(blocks)

    @staticmethod
    def _format_type(type_code):
        """Форматирование кода типа: 0xNN или расширенный 0xNNNNN"""
        if type_code > 0xFFFF:
            return '0x{0:05x}'.format(type_code)
        if type_code > 0xFF:
            return '0x{0:04x}'.format(type_code)
        return '0x{0:02x}'.format(type_code)

    def _polygon_block(self, type_code, color, label):
        lines = [
            '[_polygon]',
            'Type={0}'.format(self._format_type(type_code)),
        ]
        if label:
            lines.append('String={0}'.format(label))
        lines += [
            'Xpm="0 0 1 0"',
            '"a c {0}"'.format(color),
            '[end]',
        ]
        return lines

    def _line_block(self, type_code, color, width, border_color,
                    border_width, label):
        lines = [
            '[_line]',
            'Type={0}'.format(self._format_type(type_code)),
        ]
        if label:
            lines.append('String={0}'.format(label))
        lines.append('LineWidth={0}'.format(width))
        if border_color and border_width > 0:
            lines.append('BorderWidth={0}'.format(border_width))
            lines.append('Xpm="0 0 2 0"')
            lines.append('"a c {0}"'.format(color))
            lines.append('"b c {0}"'.format(border_color))
        else:
            lines.append('Xpm="0 0 1 0"')
            lines.append('"a c {0}"'.format(color))
        lines.append('[end]')
        return lines

    def _point_block(self, type_code, pixels, label):
        height = len(pixels)
        width = len(pixels[0])

        palette, rows = self._build_xpm_palette(pixels)

        lines = [
            '[_point]',
            'Type={0}'.format(self._format_type(type_code)),
        ]
        if label:
            lines.append('String={0}'.format(label))
        lines.append('DayXpm="{0} {1} {2} 1"'.format(
            width, height, len(palette)))
        for char, color in palette:
            lines.append('"{0} c {1}"'.format(char, color))
        for row in rows:
            lines.append('"{0}"'.format(row))
        lines.append('[end]')
        return lines

    @staticmethod
    def _build_xpm_palette(pixels):
        """Построение палитры XPM из матрицы пикселей.

        Возвращает (palette, rows):
            palette: список (символ, цвет) где цвет '#rrggbb',
                '#rrggbbaa' или 'none'
            rows: строки пиксельной карты
        """
        color_to_char = {}
        palette = []
        rows = []

        def register(color_value):
            if color_value in color_to_char:
                return color_to_char[color_value]
            index = len(palette)
            if index >= len(_XPM_CHARS):
                # Палитра переполнена - огрубляем цвет (4 бита на канал)
                if color_value not in (None, 'none') and len(color_value) >= 7:
                    coarse = '#' + ''.join(
                        color_value[i] * 2 for i in (1, 3, 5))
                    if coarse in color_to_char:
                        color_to_char[color_value] = color_to_char[coarse]
                        return color_to_char[coarse]
                    color_value = coarse
                    index = len(palette)
                    if index >= len(_XPM_CHARS):
                        return palette[0][0]
                else:
                    return palette[0][0]
            char = _XPM_CHARS[index]
            palette.append((char, color_value))
            color_to_char[color_value] = char
            return char

        for row in pixels:
            row_chars = []
            for pixel in row:
                if pixel is None:
                    row_chars.append(register('none'))
                else:
                    row_chars.append(register(pixel.lower()))
            rows.append(''.join(row_chars))

        return palette, rows


# ----------------------------------------------------------------------
# Извлечение стилей из QGIS (импорт qgis только внутри функций)
# ----------------------------------------------------------------------

def _mm_to_pixels(width_mm):
    """Пересчёт толщины линии из мм (QGIS) в пиксели устройства Garmin.

    Экраны навигаторов имеют плотность ~90-130 dpi; используем
    практичное соотношение ~4 px на мм с ограничением 1..6.
    """
    try:
        width = float(width_mm)
    except (TypeError, ValueError):
        return 2
    return max(1, min(6, int(round(width * 4)) or 1))


def _qcolor_to_hex(qcolor):
    """QColor -> '#rrggbb' (альфа игнорируется для линий/полигонов)"""
    try:
        return '#{0:02x}{1:02x}{2:02x}'.format(
            qcolor.red(), qcolor.green(), qcolor.blue())
    except Exception:
        return '#808080'


def _first_symbol(layer):
    """Первый символ рендерера слоя (для категорий - символ первой категории)"""
    renderer = layer.renderer()
    if renderer is None:
        return None
    try:
        symbols = renderer.symbols(None)
    except TypeError:
        try:
            from qgis.core import QgsRenderContext
            symbols = renderer.symbols(QgsRenderContext())
        except Exception:
            symbols = []
    except Exception:
        symbols = []
    if symbols:
        return symbols[0]
    try:
        return renderer.symbol()
    except AttributeError:
        return None


def _marker_symbol_pixels(symbol, size=16):
    """Рендер маркерного символа в матрицу пикселей для XPM"""
    try:
        from qgis.PyQt.QtCore import QSize
        image = symbol.asImage(QSize(size, size))
    except Exception:
        return None

    if image is None or image.isNull():
        return None

    pixels = []
    for y in range(image.height()):
        row = []
        for x in range(image.width()):
            rgba = image.pixelColor(x, y)
            if rgba.alpha() < 128:
                row.append(None)
            else:
                row.append('#{0:02x}{1:02x}{2:02x}'.format(
                    rgba.red(), rgba.green(), rgba.blue()))
        pixels.append(row)

    # Полностью прозрачная иконка бесполезна
    if all(pixel is None for row in pixels for pixel in row):
        return None

    return pixels


def extract_layer_style(layer):
    """Извлечение стиля слоя QGIS.

    Returns:
        словарь: {'kind': 'polygon'|'line'|'point', 'color': '#rrggbb',
                  'width_px': int, 'border_color': str|None,
                  'pixels': матрица|None}
        или None, если стиль извлечь не удалось.
    """
    from qgis.core import QgsWkbTypes

    symbol = _first_symbol(layer)
    if symbol is None:
        return None

    geom_type = layer.geometryType()

    if geom_type == QgsWkbTypes.PolygonGeometry:
        color = _qcolor_to_hex(symbol.color())
        return {'kind': 'polygon', 'color': color,
                'width_px': 0, 'border_color': None, 'pixels': None}

    if geom_type == QgsWkbTypes.LineGeometry:
        color = _qcolor_to_hex(symbol.color())
        width_px = 2
        try:
            width_px = _mm_to_pixels(symbol.width())
        except AttributeError:
            pass
        return {'kind': 'line', 'color': color,
                'width_px': width_px, 'border_color': None, 'pixels': None}

    if geom_type == QgsWkbTypes.PointGeometry:
        color = _qcolor_to_hex(symbol.color())
        pixels = _marker_symbol_pixels(symbol)
        return {'kind': 'point', 'color': color,
                'width_px': 0, 'border_color': None, 'pixels': pixels}

    return None


def build_typ_from_layers(layer_entries, family_id, product_id, code_page,
                          log_callback=None):
    """Построение typ.txt из списка слоёв.

    Args:
        layer_entries: список словарей
            {'layer': QgsVectorLayer, 'garmin_type': '0x16',
             'geometry_type': 'Polygon'}
            в порядке отрисовки сверху вниз (как в дереве слоёв)
        family_id, product_id, code_page: параметры карты
        log_callback: функция для сообщений
    Returns:
        содержимое typ.txt (str)
    """
    builder = TypFileBuilder(family_id, product_id, code_page)

    seen_types = {'polygon': set(), 'line': set(), 'point': set()}
    total = len(layer_entries)

    for index, entry in enumerate(layer_entries):
        layer = entry.get('layer')
        garmin_type = entry.get('garmin_type', '0x01')
        try:
            type_code = int(str(garmin_type), 16)
        except ValueError:
            if log_callback:
                log_callback('TYP: некорректный тип Garmin "{0}" для слоя "{1}"'.format(
                    garmin_type, entry.get('name', '?')))
            continue

        style = None
        if layer is not None:
            try:
                style = extract_layer_style(layer)
            except Exception as e:
                if log_callback:
                    log_callback('TYP: не удалось прочитать стиль слоя "{0}": {1}'.format(
                        entry.get('name', '?'), str(e)))

        if style is None:
            continue

        kind = style['kind']
        if type_code in seen_types[kind]:
            continue
        seen_types[kind].add(type_code)

        label = entry.get('name') or None

        if kind == 'polygon':
            # Слои выше в дереве рисуются поверх: больший draw_order
            draw_order = max(1, min(MAX_DRAW_ORDER, total - index))
            builder.add_polygon(type_code, style['color'], draw_order, label)
        elif kind == 'line':
            builder.add_line(type_code, style['color'],
                             style['width_px'], label=label)
        elif kind == 'point':
            if style['pixels']:
                builder.add_point(type_code, style['pixels'], label)
            # POI без иконки оставляем стандартному стилю Garmin

    return builder.build()
